DROP TABLE IF EXISTS sender;
DROP TABLE IF EXISTS receiver;
DROP TABLE IF EXISTS resi;
DROP TABLE IF EXISTS package;
DROP TABLE IF EXISTS package_detail;
DROP TABLE IF EXISTS package_type;
DROP TABLE IF EXISTS service_type;
