DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS page;
DROP TABLE IF EXISTS context;
DROP TABLE IF EXISTS credential;
DROP TABLE IF EXISTS branch;
DROP TABLE IF EXISTS misc;
DROP TABLE IF EXISTS country;
